package Model;
// Generated Jun 29, 2017 6:13:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Certificacion generated by hbm2java
 */
public class Certificacion  implements java.io.Serializable {


     private CertificacionId id;
     private Cobrador cobrador;
     private Integer faltante;
     private Integer sobrante;
     private Integer discrepancias;
     private Date fechaOperativa;

    public Certificacion() {
    }

	
    public Certificacion(CertificacionId id, Cobrador cobrador) {
        this.id = id;
        this.cobrador = cobrador;
    }
    public Certificacion(CertificacionId id, Cobrador cobrador, Integer faltante, Integer sobrante, Integer discrepancias, Date fechaOperativa) {
       this.id = id;
       this.cobrador = cobrador;
       this.faltante = faltante;
       this.sobrante = sobrante;
       this.discrepancias = discrepancias;
       this.fechaOperativa = fechaOperativa;
    }
   
    public CertificacionId getId() {
        return this.id;
    }
    
    public void setId(CertificacionId id) {
        this.id = id;
    }
    public Cobrador getCobrador() {
        return this.cobrador;
    }
    
    public void setCobrador(Cobrador cobrador) {
        this.cobrador = cobrador;
    }
    public Integer getFaltante() {
        return this.faltante;
    }
    
    public void setFaltante(Integer faltante) {
        this.faltante = faltante;
    }
    public Integer getSobrante() {
        return this.sobrante;
    }
    
    public void setSobrante(Integer sobrante) {
        this.sobrante = sobrante;
    }
    public Integer getDiscrepancias() {
        return this.discrepancias;
    }
    
    public void setDiscrepancias(Integer discrepancias) {
        this.discrepancias = discrepancias;
    }
    public Date getFechaOperativa() {
        return this.fechaOperativa;
    }
    
    public void setFechaOperativa(Date fechaOperativa) {
        this.fechaOperativa = fechaOperativa;
    }




}


