package Model;
// Generated Jun 29, 2017 6:13:26 PM by Hibernate Tools 4.3.1



/**
 * CertificacionId generated by hbm2java
 */
public class CertificacionId  implements java.io.Serializable {


     private int idCertificacion;
     private int cobradorIdNumeroEmpleado;

    public CertificacionId() {
    }

    public CertificacionId(int idCertificacion, int cobradorIdNumeroEmpleado) {
       this.idCertificacion = idCertificacion;
       this.cobradorIdNumeroEmpleado = cobradorIdNumeroEmpleado;
    }
   
    public int getIdCertificacion() {
        return this.idCertificacion;
    }
    
    public void setIdCertificacion(int idCertificacion) {
        this.idCertificacion = idCertificacion;
    }
    public int getCobradorIdNumeroEmpleado() {
        return this.cobradorIdNumeroEmpleado;
    }
    
    public void setCobradorIdNumeroEmpleado(int cobradorIdNumeroEmpleado) {
        this.cobradorIdNumeroEmpleado = cobradorIdNumeroEmpleado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CertificacionId) ) return false;
		 CertificacionId castOther = ( CertificacionId ) other; 
         
		 return (this.getIdCertificacion()==castOther.getIdCertificacion())
 && (this.getCobradorIdNumeroEmpleado()==castOther.getCobradorIdNumeroEmpleado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCertificacion();
         result = 37 * result + this.getCobradorIdNumeroEmpleado();
         return result;
   }   


}


