package Model;
// Generated Jun 29, 2017 6:13:26 PM by Hibernate Tools 4.3.1



/**
 * Eludidos generated by hbm2java
 */
public class Eludidos  implements java.io.Serializable {


     private EludidosId id;
     private Evento evento;
     private String formaEludir;
     private Integer efectivoArrojado;

    public Eludidos() {
    }

	
    public Eludidos(EludidosId id, Evento evento) {
        this.id = id;
        this.evento = evento;
    }
    public Eludidos(EludidosId id, Evento evento, String formaEludir, Integer efectivoArrojado) {
       this.id = id;
       this.evento = evento;
       this.formaEludir = formaEludir;
       this.efectivoArrojado = efectivoArrojado;
    }
   
    public EludidosId getId() {
        return this.id;
    }
    
    public void setId(EludidosId id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public String getFormaEludir() {
        return this.formaEludir;
    }
    
    public void setFormaEludir(String formaEludir) {
        this.formaEludir = formaEludir;
    }
    public Integer getEfectivoArrojado() {
        return this.efectivoArrojado;
    }
    
    public void setEfectivoArrojado(Integer efectivoArrojado) {
        this.efectivoArrojado = efectivoArrojado;
    }




}


