package Model;
// Generated Jun 29, 2017 6:13:26 PM by Hibernate Tools 4.3.1



/**
 * EventoId generated by hbm2java
 */
public class EventoId  implements java.io.Serializable {


     private int idFolioSistema;
     private int supervisorIdNumeroEmpleado;
     private int cobradorIdNumeroEmpleado;
     private int periodosTarifasIdPeriodoTarifa;

    public EventoId() {
    }

    public EventoId(int idFolioSistema, int supervisorIdNumeroEmpleado, int cobradorIdNumeroEmpleado, int periodosTarifasIdPeriodoTarifa) {
       this.idFolioSistema = idFolioSistema;
       this.supervisorIdNumeroEmpleado = supervisorIdNumeroEmpleado;
       this.cobradorIdNumeroEmpleado = cobradorIdNumeroEmpleado;
       this.periodosTarifasIdPeriodoTarifa = periodosTarifasIdPeriodoTarifa;
    }
   
    public int getIdFolioSistema() {
        return this.idFolioSistema;
    }
    
    public void setIdFolioSistema(int idFolioSistema) {
        this.idFolioSistema = idFolioSistema;
    }
    public int getSupervisorIdNumeroEmpleado() {
        return this.supervisorIdNumeroEmpleado;
    }
    
    public void setSupervisorIdNumeroEmpleado(int supervisorIdNumeroEmpleado) {
        this.supervisorIdNumeroEmpleado = supervisorIdNumeroEmpleado;
    }
    public int getCobradorIdNumeroEmpleado() {
        return this.cobradorIdNumeroEmpleado;
    }
    
    public void setCobradorIdNumeroEmpleado(int cobradorIdNumeroEmpleado) {
        this.cobradorIdNumeroEmpleado = cobradorIdNumeroEmpleado;
    }
    public int getPeriodosTarifasIdPeriodoTarifa() {
        return this.periodosTarifasIdPeriodoTarifa;
    }
    
    public void setPeriodosTarifasIdPeriodoTarifa(int periodosTarifasIdPeriodoTarifa) {
        this.periodosTarifasIdPeriodoTarifa = periodosTarifasIdPeriodoTarifa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventoId) ) return false;
		 EventoId castOther = ( EventoId ) other; 
         
		 return (this.getIdFolioSistema()==castOther.getIdFolioSistema())
 && (this.getSupervisorIdNumeroEmpleado()==castOther.getSupervisorIdNumeroEmpleado())
 && (this.getCobradorIdNumeroEmpleado()==castOther.getCobradorIdNumeroEmpleado())
 && (this.getPeriodosTarifasIdPeriodoTarifa()==castOther.getPeriodosTarifasIdPeriodoTarifa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFolioSistema();
         result = 37 * result + this.getSupervisorIdNumeroEmpleado();
         result = 37 * result + this.getCobradorIdNumeroEmpleado();
         result = 37 * result + this.getPeriodosTarifasIdPeriodoTarifa();
         return result;
   }   


}


