package Model;
// Generated Jun 29, 2017 6:13:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private EventoId id;
     private Cobrador cobrador;
     private Periodostarifas periodostarifas;
     private Supervisor supervisor;
     private String plazaCobro;
     private Date fechaOperativa;
     private Date fechaHoraEvento;
     private String turno;
     private String via;
     private Integer ticket;
     private String modoPago;
     private String modoPaso;
     private String modoPasoVerificado;
     private String tarjetaTelepeaje;
     private String claseTabulada;
     private String claseDetectada;
     private String claseVerificada;
     private Integer importe;
     private String observaciones;
     private Set eludidoses = new HashSet(0);

    public Evento() {
    }

	
    public Evento(EventoId id, Cobrador cobrador, Periodostarifas periodostarifas, Supervisor supervisor) {
        this.id = id;
        this.cobrador = cobrador;
        this.periodostarifas = periodostarifas;
        this.supervisor = supervisor;
    }
    public Evento(EventoId id, Cobrador cobrador, Periodostarifas periodostarifas, Supervisor supervisor, String plazaCobro, Date fechaOperativa, Date fechaHoraEvento, String turno, String via, Integer ticket, String modoPago, String modoPaso, String modoPasoVerificado, String tarjetaTelepeaje, String claseTabulada, String claseDetectada, String claseVerificada, Integer importe, String observaciones, Set eludidoses) {
       this.id = id;
       this.cobrador = cobrador;
       this.periodostarifas = periodostarifas;
       this.supervisor = supervisor;
       this.plazaCobro = plazaCobro;
       this.fechaOperativa = fechaOperativa;
       this.fechaHoraEvento = fechaHoraEvento;
       this.turno = turno;
       this.via = via;
       this.ticket = ticket;
       this.modoPago = modoPago;
       this.modoPaso = modoPaso;
       this.modoPasoVerificado = modoPasoVerificado;
       this.tarjetaTelepeaje = tarjetaTelepeaje;
       this.claseTabulada = claseTabulada;
       this.claseDetectada = claseDetectada;
       this.claseVerificada = claseVerificada;
       this.importe = importe;
       this.observaciones = observaciones;
       this.eludidoses = eludidoses;
    }
   
    public EventoId getId() {
        return this.id;
    }
    
    public void setId(EventoId id) {
        this.id = id;
    }
    public Cobrador getCobrador() {
        return this.cobrador;
    }
    
    public void setCobrador(Cobrador cobrador) {
        this.cobrador = cobrador;
    }
    public Periodostarifas getPeriodostarifas() {
        return this.periodostarifas;
    }
    
    public void setPeriodostarifas(Periodostarifas periodostarifas) {
        this.periodostarifas = periodostarifas;
    }
    public Supervisor getSupervisor() {
        return this.supervisor;
    }
    
    public void setSupervisor(Supervisor supervisor) {
        this.supervisor = supervisor;
    }
    public String getPlazaCobro() {
        return this.plazaCobro;
    }
    
    public void setPlazaCobro(String plazaCobro) {
        this.plazaCobro = plazaCobro;
    }
    public Date getFechaOperativa() {
        return this.fechaOperativa;
    }
    
    public void setFechaOperativa(Date fechaOperativa) {
        this.fechaOperativa = fechaOperativa;
    }
    public Date getFechaHoraEvento() {
        return this.fechaHoraEvento;
    }
    
    public void setFechaHoraEvento(Date fechaHoraEvento) {
        this.fechaHoraEvento = fechaHoraEvento;
    }
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }
    public String getVia() {
        return this.via;
    }
    
    public void setVia(String via) {
        this.via = via;
    }
    public Integer getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Integer ticket) {
        this.ticket = ticket;
    }
    public String getModoPago() {
        return this.modoPago;
    }
    
    public void setModoPago(String modoPago) {
        this.modoPago = modoPago;
    }
    public String getModoPaso() {
        return this.modoPaso;
    }
    
    public void setModoPaso(String modoPaso) {
        this.modoPaso = modoPaso;
    }
    public String getModoPasoVerificado() {
        return this.modoPasoVerificado;
    }
    
    public void setModoPasoVerificado(String modoPasoVerificado) {
        this.modoPasoVerificado = modoPasoVerificado;
    }
    public String getTarjetaTelepeaje() {
        return this.tarjetaTelepeaje;
    }
    
    public void setTarjetaTelepeaje(String tarjetaTelepeaje) {
        this.tarjetaTelepeaje = tarjetaTelepeaje;
    }
    public String getClaseTabulada() {
        return this.claseTabulada;
    }
    
    public void setClaseTabulada(String claseTabulada) {
        this.claseTabulada = claseTabulada;
    }
    public String getClaseDetectada() {
        return this.claseDetectada;
    }
    
    public void setClaseDetectada(String claseDetectada) {
        this.claseDetectada = claseDetectada;
    }
    public String getClaseVerificada() {
        return this.claseVerificada;
    }
    
    public void setClaseVerificada(String claseVerificada) {
        this.claseVerificada = claseVerificada;
    }
    public Integer getImporte() {
        return this.importe;
    }
    
    public void setImporte(Integer importe) {
        this.importe = importe;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set getEludidoses() {
        return this.eludidoses;
    }
    
    public void setEludidoses(Set eludidoses) {
        this.eludidoses = eludidoses;
    }




}


