package Model;
// Generated Jun 29, 2017 6:13:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Periodostarifas generated by hbm2java
 */
public class Periodostarifas  implements java.io.Serializable {


     private int idPeriodoTarifa;
     private Date fechaInicio;
     private Date fechaFinal;
     private Integer m;
     private Integer a;
     private Integer ar1;
     private Integer ar2;
     private Integer ar3;
     private Integer b2;
     private Integer b3;
     private Integer b4;
     private Integer c2;
     private Integer c3;
     private Integer c4;
     private Integer c5;
     private Integer c6;
     private Integer c7;
     private Integer c8;
     private Integer c9;
     private Integer eel;
     private Integer eep;
     private Set eventos = new HashSet(0);

    public Periodostarifas() {
    }

	
    public Periodostarifas(int idPeriodoTarifa) {
        this.idPeriodoTarifa = idPeriodoTarifa;
    }
    public Periodostarifas(int idPeriodoTarifa, Date fechaInicio, Date fechaFinal, Integer m, Integer a, Integer ar1, Integer ar2, Integer ar3, Integer b2, Integer b3, Integer b4, Integer c2, Integer c3, Integer c4, Integer c5, Integer c6, Integer c7, Integer c8, Integer c9, Integer eel, Integer eep, Set eventos) {
       this.idPeriodoTarifa = idPeriodoTarifa;
       this.fechaInicio = fechaInicio;
       this.fechaFinal = fechaFinal;
       this.m = m;
       this.a = a;
       this.ar1 = ar1;
       this.ar2 = ar2;
       this.ar3 = ar3;
       this.b2 = b2;
       this.b3 = b3;
       this.b4 = b4;
       this.c2 = c2;
       this.c3 = c3;
       this.c4 = c4;
       this.c5 = c5;
       this.c6 = c6;
       this.c7 = c7;
       this.c8 = c8;
       this.c9 = c9;
       this.eel = eel;
       this.eep = eep;
       this.eventos = eventos;
    }
   
    public int getIdPeriodoTarifa() {
        return this.idPeriodoTarifa;
    }
    
    public void setIdPeriodoTarifa(int idPeriodoTarifa) {
        this.idPeriodoTarifa = idPeriodoTarifa;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public Integer getM() {
        return this.m;
    }
    
    public void setM(Integer m) {
        this.m = m;
    }
    public Integer getA() {
        return this.a;
    }
    
    public void setA(Integer a) {
        this.a = a;
    }
    public Integer getAr1() {
        return this.ar1;
    }
    
    public void setAr1(Integer ar1) {
        this.ar1 = ar1;
    }
    public Integer getAr2() {
        return this.ar2;
    }
    
    public void setAr2(Integer ar2) {
        this.ar2 = ar2;
    }
    public Integer getAr3() {
        return this.ar3;
    }
    
    public void setAr3(Integer ar3) {
        this.ar3 = ar3;
    }
    public Integer getB2() {
        return this.b2;
    }
    
    public void setB2(Integer b2) {
        this.b2 = b2;
    }
    public Integer getB3() {
        return this.b3;
    }
    
    public void setB3(Integer b3) {
        this.b3 = b3;
    }
    public Integer getB4() {
        return this.b4;
    }
    
    public void setB4(Integer b4) {
        this.b4 = b4;
    }
    public Integer getC2() {
        return this.c2;
    }
    
    public void setC2(Integer c2) {
        this.c2 = c2;
    }
    public Integer getC3() {
        return this.c3;
    }
    
    public void setC3(Integer c3) {
        this.c3 = c3;
    }
    public Integer getC4() {
        return this.c4;
    }
    
    public void setC4(Integer c4) {
        this.c4 = c4;
    }
    public Integer getC5() {
        return this.c5;
    }
    
    public void setC5(Integer c5) {
        this.c5 = c5;
    }
    public Integer getC6() {
        return this.c6;
    }
    
    public void setC6(Integer c6) {
        this.c6 = c6;
    }
    public Integer getC7() {
        return this.c7;
    }
    
    public void setC7(Integer c7) {
        this.c7 = c7;
    }
    public Integer getC8() {
        return this.c8;
    }
    
    public void setC8(Integer c8) {
        this.c8 = c8;
    }
    public Integer getC9() {
        return this.c9;
    }
    
    public void setC9(Integer c9) {
        this.c9 = c9;
    }
    public Integer getEel() {
        return this.eel;
    }
    
    public void setEel(Integer eel) {
        this.eel = eel;
    }
    public Integer getEep() {
        return this.eep;
    }
    
    public void setEep(Integer eep) {
        this.eep = eep;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


