package Model;
// Generated Jun 29, 2017 6:13:26 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Supervisor generated by hbm2java
 */
public class Supervisor  implements java.io.Serializable {


     private int idNumeroEmpleado;
     private String nombre;
     private Date fechaIngreso;
     private Set eventos = new HashSet(0);

    public Supervisor() {
    }

	
    public Supervisor(int idNumeroEmpleado) {
        this.idNumeroEmpleado = idNumeroEmpleado;
    }
    public Supervisor(int idNumeroEmpleado, String nombre, Date fechaIngreso, Set eventos) {
       this.idNumeroEmpleado = idNumeroEmpleado;
       this.nombre = nombre;
       this.fechaIngreso = fechaIngreso;
       this.eventos = eventos;
    }
   
    public int getIdNumeroEmpleado() {
        return this.idNumeroEmpleado;
    }
    
    public void setIdNumeroEmpleado(int idNumeroEmpleado) {
        this.idNumeroEmpleado = idNumeroEmpleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


